// <auto-generated />
using System;
using Bolao.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bolao.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527195115_MakeBolaoInviteCodeNullable")]
    partial class MakeBolaoInviteCodeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bolao.Domain.Entities.Bolao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Championship")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Privacy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("[InviteCode] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("Boloes", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.BolaoMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BolaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BolaoId", "UserId")
                        .IsUnique();

                    b.ToTable("BolaoMembers", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.BolaoRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BolaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DrawPoints")
                        .HasColumnType("int");

                    b.Property<int>("ExactScorePoints")
                        .HasColumnType("int");

                    b.Property<int>("GoalsPoints")
                        .HasColumnType("int");

                    b.Property<int>("WinnerPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolaoId")
                        .IsUnique();

                    b.ToTable("BolaoRules", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Bolao", b =>
                {
                    b.HasOne("Bolao.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.BolaoMember", b =>
                {
                    b.HasOne("Bolao.Domain.Entities.Bolao", "Bolao")
                        .WithMany()
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bolao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.BolaoRules", b =>
                {
                    b.HasOne("Bolao.Domain.Entities.Bolao", "Bolao")
                        .WithOne("Rules")
                        .HasForeignKey("Bolao.Domain.Entities.BolaoRules", "BolaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolao");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Bolao", b =>
                {
                    b.Navigation("Rules")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
